#!/bin/bash

name=$1
[ -z "${name}" ] && echo "need to pass cluster-name" && exit 1
region=$2
[ -z "${region}" ] && echo "need to pass regsion" && exit 1

filter="Name=tag:KubernetesCluster,Values=${name}"

( \
  printf "instance-id\tstate\tname\trole\tKubernetesCluster\tprivate-ip\tpublic-ip\n" ;\
  aws ec2 describe-instances \
    --output text \
    --filters "Name=instance-state-name,Values=running" ${filter} \
    --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Name`].Value|[0],Tags[?Key==`role`].Value|[0],Tags[?Key==`KubernetesCluster`].Value|[0],PrivateIpAddress,PublicIpAddress]' \
    --region ${region}
  aws ec2 describe-instances \
    --output text \
    --filters "Name=instance-state-name,Values=running,Name=tag:role,Values=pki" \
    --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Name`].Value|[0],Tags[?Key==`role`].Value|[0],Tags[?Key==`KubernetesCluster`].Value|[0],PrivateIpAddress,PublicIpAddress]' \
    --region ${region}
) | column -t -s $'\t'
